### ISSUE TITLE
Standard readme text

### ISSUE THREAD

**Issue by vectorsize** [Ircam-RnD/waves#8]
we need to replace the current readmes with a standard message and link to the docs.
see [here](https://github.com/jashkenas/backbone) for an example.

**Comment by vectorsize** [comment]
This becomes a nice place for interlinking with wave.ircam.fr, license (partners?) and all that jazz

**Comment by b-ma** [comment]
Something like the following would be ok ?

# WAVE.JS - Segment Component

_Use this module to visualise and edit data segments over a shared timeline._

This component is part of the `waves.js` library ([https://github.com/Ircam-RnD/waves](https://github.com/Ircam-RnD/waves)) and relies on a [timeline](https://github.com/ircam-rnd/timeline) instance

Documentation of the component can be found at [http://ircam-rnd.github.io/waves/#ui-segment](http://ircam-rnd.github.io/waves/#ui-segment)

## License

This module is released under the [BSD-3-Clause license](http://opensource.org/licenses/BSD-3-Clause).

## Acknowledgments

This code is part of the [WAVE project](http://wave.ircam.fr), funded by ANR (The French National Research Agency),  
_ContInt_ program, 2012-2015.
